name: GitEvents ICS Generator

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: GitEvents ICS Generator
        uses: gitevents/ics@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          default-timezone: 'Europe/Athens'
          locations: 'locations.json'
      - name: update .ics file
        run: |
          git config user.name cdc.cy
          git config user.email ics@cdc.cy
          git add events.ics
          git commit -m "Update calendar file"
          git push
