name: Create Events on Discord & Twitter

on:
  issues:
    types: [labeled]

jobs:
  twitter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print event
        run: echo "${{ toJSON(github)}}"
  # discord:
  #   if: contains( github.event.issue.labels.*.name, 'Approved' )
  #   uses: gitevents/propaganda/.github/workflows/discord-event.yml@main
  #   with:
  #     server-id: "855088264180400198"
  #     time-zone: 'Europe/Nicosia'
  # twitter:
  #   uses: gitevents/propaganda/.github/workflows/twitter-event.yml@main
  #   with:
  #     status: 'event content'
  #   secrets:
  #     consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
  #     consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  #     access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  #     access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}